# Tensor Flow Syntax

In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

1.4.0


In [4]:
hello = tf.constant("hello")
world = tf.constant("world")

In [5]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [6]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [7]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [8]:
print(result)

b'helloworld'


In [9]:
a = tf.constant(10)
b = tf.constant(20)

In [10]:
with tf.Session() as sess:
    result = sess.run(a+b)
print(result)

30


In [11]:
a = tf.constant(10)
fill_mat = tf.fill((4,4),4.1,name = "AMatrix")
print(fill_mat)

Tensor("AMatrix:0", shape=(4, 4), dtype=float32)


In [12]:
with tf.Session() as sess:
    result = sess.run(fill_mat)
    print(result)

[[ 4.0999999  4.0999999  4.0999999  4.0999999]
 [ 4.0999999  4.0999999  4.0999999  4.0999999]
 [ 4.0999999  4.0999999  4.0999999  4.0999999]
 [ 4.0999999  4.0999999  4.0999999  4.0999999]]


In [15]:
ones = tf.ones((10,10))
zeroes = tf.zeros((10,10))
randn = tf.random_normal(mean=1,stddev=1,shape=(10,10))
randu = tf.random_uniform((10,10),maxval=10,minval=1,seed=2)
with tf.Session() as sess:
    print("Ones")
    print(sess.run(ones))
    print("Zeroes")
    print(sess.run(zeroes))
    print("Normal Distribution")
    print(sess.run(randn))
    print("Uniform Distribution")
    print(sess.run(randu))

Ones
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
Zeroes
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
Normal Distribution
[[ 0.89710629  1.18422103  2.26436043  1.04145753  2.69149923  1.0171932
   2.49739051  2.57187891  1.5073

In [23]:
sess =tf.InteractiveSession()
my_ops = [ones,zeroes,randn,randu]
for op in my_ops:
    print(sess.run(op))

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 1.93654108  1.23989522  2.10384798  0.88223708  0.04505837  0.76362157
   0.98826104 -2.12209105  1.18866467  3.17164731]
 [-0.79812706

In [24]:
a =tf.constant([[1,2],
               [2,4],
               [3,5]])
a.get_shape()
sess.run(a)

array([[1, 2],
       [2, 4],
       [3, 5]])

# Tensorflow Graphs

In [25]:
n1 = tf.constant(1)
n2 = tf.constant(2)

In [26]:
n3 = n1+n2 

In [27]:
with tf.Session() as sess:
    result = sess.run(n3)
    print(result)

3


In [36]:
# Changing Graphs to a Default Graph.

print(tf.get_default_graph())
g = tf.Graph()
g1 = tf.Graph()
print(g)
print(g1)

In [37]:
with g1.as_default():
    print(g1 is tf.get_default_graph())

print(g1 is tf.get_default_graph())

True
False


In [38]:
sess.close()

# Tensorflow : Varibale and PlaceHolders

In [40]:
sess  = tf.InteractiveSession()

In [41]:
tensor = tf.random_uniform((4,4),0,1)

In [42]:
my_var = tf.Variable(initial_value=tensor)

## Initialize Varibales and PlaceHolders.

In [43]:
init = tf.global_variables_initializer()

In [44]:
sess.run(init)

In [45]:
sess.run(my_var)

array([[ 0.69879997,  0.13603294,  0.22047865,  0.21360469],
       [ 0.92270434,  0.55468488,  0.13692915,  0.75311697],
       [ 0.28504646,  0.40987182,  0.27648664,  0.47836256],
       [ 0.18144393,  0.16517663,  0.95676339,  0.72317457]], dtype=float32)

In [47]:
ph = tf.placeholder(dtype=tf.float32,shape=(None,5))

# First Neural Network Model

$$ Y = wx + b $$
Type
$$ w = Variable $$
$$ x = PlaceHolder $$
$$ b = Variable $$
Activation Function : __Sigmoid__

In [49]:
import numpy as np 
import pandas as pd 

In [53]:
np.random.seed(101)
tf.set_random_seed(101)

In [87]:
# Both represents the same
rand_a_np = np.random.uniform(0,100,(5,5))
rand_a = tf.random_uniform(shape=(5,5),maxval=100,minval=0)


In [88]:
rand_b_np = np.random.uniform(0,100,(5,1))
rand_b = tf.random_uniform(shape=(5,1),maxval=100,minval=0)

In [89]:
a = tf.placeholder(dtype=tf.float32)

In [91]:
b = tf.placeholder(dtype=tf.float32)

In [92]:
# tf.matmul(a,b)
add_op = a+b
mul_op = a*b

In [96]:
# Feed Values to the place holders using feed_dict parameter.
# This is just a warm Up.

with tf.Session() as sess:
    add_result = sess.run(add_op,feed_dict = {a:rand_a_np,b:rand_b_np})
    mul_result = sess.run(mul_op,feed_dict = {a:rand_a_np,b:rand_b_np})
    print(rand_a_np)
    print(rand_b_np)
    print(add_result)
    print(mul_result)

[[  8.01035387  60.72162718  63.08467036  37.79419319   1.32410111]
 [ 84.22194119  38.49377461  55.16658451  71.05381401  67.52788507]
 [ 69.45646648  34.24567679  41.23905637  23.97909655  96.88359762]
 [ 28.85570076  14.73116127  12.93404399  94.40560505  35.14342645]
 [ 73.35676132  91.38895268  70.09874942  38.8531272   94.22592889]]
[[ 73.64913313]
 [ 23.8464388 ]
 [ 82.37737283]
 [ 76.06134452]
 [ 39.4709074 ]]
[[  81.65948486  134.37075806  136.73379517  111.44332886   74.97323608]
 [ 108.06837463   62.34021378   79.01302338   94.9002533    91.37432861]
 [ 151.83383179  116.62304688  123.61642456  106.3564682   179.26097107]
 [ 104.91705322   90.79251099   88.99539185  170.46694946  111.20477295]
 [ 112.82766724  130.85986328  109.56965637   78.32403564  133.69683838]]
[[  589.95562744  4472.09521484  4646.13134766  2783.50952148
     97.51889801]
 [ 2008.39331055   917.93945312  1315.52661133  1694.38061523
   1610.29968262]
 [ 5721.64111328  2821.0690918   3397.16503906  1975

In [97]:
n_features = 10 
n_dense_neurons = 3 

In [100]:
x = tf.placeholder(dtype=tf.float32,shape=(None,n_features))

In [104]:
W = tf.Variable(tf.random_normal(shape = (n_features,n_dense_neurons),mean=1,stddev = 2))

b = tf.Variable(tf.ones([n_dense_neurons]))

xW = tf.matmul(x,W)

In [105]:
z = tf.add(xW,b)

In [106]:
activationFun = tf.nn.sigmoid(z)

In [112]:
init = tf.global_variables_initializer()

In [115]:
with tf.Session() as sess:
    sess.run(init)
    layer_out = sess.run(activationFun,feed_dict={x:np.random.random(size=[1,n_features])})
    print(layer_out)

[[ 0.99997926  0.97765428  0.99999368]]
